### ISSUE TITLE
Hydration fails when project is build first.

### ISSUE THREAD

**Issue by JanKaul** [lumeland/react-todo#3]
First of all, thank you for the awesome lume project. 

I'm running into an issue when I build the react-todo repo before I run the server. When I run `deno task build` before I run `deno task serve` I get the Error:

```
There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

I guess this is because the site is served from the statically generated file instead of the dynamic server component.

Do you have any idea why the statically generated html does not match the one rendered on the server? Or do you have an idea how one could create a statically generated site at build time that is hydrated with React on the client?

**Comment by oscarotero** [comment]
Yes, I noted it but wasn't able to fix it.
The reported error is the following:

<img width="789" alt="imaxe" src="https://github.com/lumeland/react-todo/assets/377873/60acfacf-1cb6-4960-8674-4eaf4f3445ea">

My guess is when the DOM is generated on build time, there're no to-dos (because they are stored in the localstorage, on browser side), so the `<section class="main">` and `<footer class="footer">` are not rendered and React might detect the DOM is too different. But it makes no sense to me, because the other DOM elements (headers and root) matches.

**Comment by JanKaul** [comment]
Thanks for looking into it. I'll try to figure out where the difference comes from.

**Comment by JanKaul** [comment]
I think I found the issue. It comes from the ToDo items stored in `LocalStorage`. When you load the page for the first time or with empty `LocalStorage` the error doesn't occur. It only occurs when you have added ToDo items to the list. Which makes sense because they cannot be present in the DOM at build time.

**Comment by oscarotero** [comment]
Yes, that's what I thought. I (wrongly) assumed hydration would complete the DOM if the data was different, but looks like it only work if the same data is used in server and client side, which makes sense for data stored on backend (like a database) but not if the data is available only on the browser.
